language: generic
services:
- docker
jobs:
  include:
    - stage: Build test container and run tests
      script:
        - docker build --target test --tag todo-app:test .
        - docker run todo-app:test test_app.py 
        - docker run --env-file ./.env.test todo-app:test test_integration.py
        - docker run -e SECRET_KEY -e CLIENT_ID -e CLIENT_SECRET -e COSMOS_CONNECTION_STRING -e DATABASE_NAME -e LOGGLY_KEY todo-app:test test_selenium.py

    - stage: Build and push production images
      install:
        - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
        - unzip terraform_"$TF_VERSION"_linux_amd64.zip
        - sudo mv terraform /usr/local/bin/
        - rm terraform_"$TF_VERSION"_linux_amd64.zip
        - terraform init
      before_deploy:
        - echo "$docker_pswd" | docker login -u "$docker_username" --password-stdin
        - docker build --target production --tag gontx/todo-app:latest .
        - docker push gontx/todo-app:latest
        - terraform apply -var client_id=$CLIENT_ID -var client_secret=$CLIENT_SECRET -var secret_key=$SECRET_KEY -var LOGGLY_TOKEN=$LOGGLY_TOKEN -var DATABASE_NAME=$DATABASE_NAME -auto-approve
      deploy:
        provider: script
        script: 
            - bash webhook.sh
        on:
          branch: 
            - main
            - exercise-8
            - exercise-11
            - exercise-12
            - exercise-13
